import { WorkItemPriority } from '../../../domain/enums/work-item-priority.enum'
import { WorkItemType } from '../../../domain/enums/work-item-type.enum'

/**
 * Input required to create a new work item.
 *
 * Work item key and number are intentionally excluded because
 * they are generated by the application layer.
 */
export interface CreateWorkItemInput {
  readonly workspaceId: string
  readonly projectId: string
  readonly teamId: string

  readonly type?: WorkItemType

  readonly title: string
  readonly description?: string | null
  readonly acceptanceCriteria?: readonly string[]

  readonly parentId?: string | null

  readonly priority?: WorkItemPriority | null

  readonly sprintId?: string | null
  readonly assigneeId?: string | null

  readonly actorId: string

  readonly storyPoints?: number | null

  readonly startedAt?: Date | null
  readonly dueDate?: Date | null
}
