import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "@orbit/ui/globals.css";
import { cn } from "@orbit/ui/lib/utils";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "../../../packages/ui/src/components/sidebar";
import { AppSidebar } from "@/components/admin-sidebar";
import { TooltipProvider } from "../../../packages/ui/src/components/tooltip";
import { QueryProvider } from "./api/query";
import { ErrorDialog } from "@/error";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-dvh min-w-dvw flex flex-col">
        <QueryProvider>
          <TooltipProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <header className="sticky top-0 z-40 flex h-16 items-center gap-3 border-b bg-background/80 px-4 backdrop-blur">
                  <SidebarTrigger />
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium">Admin Panel</span>
                  </div>
                </header>
                <main className="p-4 md:p-6">{children}</main>
              </SidebarInset>
            </SidebarProvider>
          </TooltipProvider>
          <ErrorDialog/>
        </QueryProvider>
      </body>
    </html>
  );
}
